# Generated by Django 3.0.3 on 2020-03-27 17:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('head', models.ImageField(default='user/201809/23/tx1.png', upload_to='head/%Y/%m', verbose_name='用户头像')),
                ('nick_name', models.CharField(max_length=50, verbose_name='昵称')),
                ('openid', models.CharField(blank=True, max_length=32, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyHring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('job_name', models.CharField(blank=True, max_length=16, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.CharField(blank=True, max_length=16, null=True)),
                ('scope_commission', models.CharField(blank=True, max_length=16, null=True)),
                ('work_des', models.TextField(blank=True, null=True)),
                ('nature', models.CharField(blank=True, max_length=32, null=True)),
                ('work_nature', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.CharField(blank=True, max_length=8, null=True)),
                ('sex', models.CharField(blank=True, max_length=8, null=True)),
                ('experience', models.CharField(blank=True, max_length=8, null=True)),
                ('certificate', models.CharField(blank=True, max_length=32, null=True)),
                ('education', models.CharField(blank=True, max_length=8, null=True)),
                ('user', models.CharField(blank=True, max_length=8, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('is_call', models.BooleanField(default=False, verbose_name='是否允许打电话')),
                ('status', models.CharField(choices=[('on', '招聘中'), ('stop', '暂停招聘'), ('full', '招满')], default='on', max_length=6)),
            ],
            options={
                'verbose_name': '岗位信息',
                'db_table': 'company_hring',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '职位表',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '职位类型表',
                'db_table': 'position_type',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('real_name', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('city', models.CharField(default='', max_length=16)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('wx_num', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='微信号')),
                ('cur_status', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='当前身份')),
                ('entry_time', models.DateField(blank=True, null=True, verbose_name='入行时间')),
                ('pro_certificate', models.ImageField(default='pro/201809/23/tx1.png', upload_to='pro/%Y/%m', verbose_name='从业证书')),
                ('id_verify', models.ImageField(default='id/201809/23/tx1.png', upload_to='id/%Y/%m', verbose_name='身份证')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='自我介绍')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='兴趣爱好')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Position')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简历表',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('company_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='公司名称')),
                ('entry_time', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('resignation_time', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('job_content', models.TextField(blank=True, max_length=128, null=True, verbose_name='工作内容')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Position')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作经历',
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='User2Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.CompanyHring')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'position_user',
            },
        ),
        migrations.CreateModel(
            name='StoreAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_verify', models.BooleanField(default=False, verbose_name='是否审核')),
                ('company_name', models.CharField(blank=True, max_length=32, null=True)),
                ('open_time', models.DateField(blank=True, null=True)),
                ('addr', models.CharField(blank=True, max_length=32, null=True)),
                ('shop_pic', models.ImageField(default='shop/201809/23/tx1.png', upload_to='shop/%Y/%m', verbose_name='店铺照片')),
                ('business_licens', models.ImageField(default='business/201809/23/tx1.png', upload_to='business/%Y/%m', verbose_name='营业执照')),
                ('name', models.CharField(blank=True, max_length=8, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('entry_time', models.DateField(blank=True, null=True)),
                ('id_verify', models.ImageField(default='id/201809/23/tx1.png', upload_to='id/%Y/%m', verbose_name='身份证')),
                ('wx', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '店铺认证',
                'db_table': 'store_authentication',
            },
        ),
        migrations.CreateModel(
            name='SkillLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=16, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Position')),
            ],
            options={
                'verbose_name': '技能标签',
                'db_table': 'skill_label',
            },
        ),
        migrations.CreateModel(
            name='Skill2Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Resume')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.SkillLabel')),
            ],
            options={
                'db_table': 'skill_resume',
            },
        ),
        migrations.CreateModel(
            name='Resume2Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Resume')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.StoreAuthentication')),
            ],
            options={
                'db_table': 'store_resume',
            },
        ),
        migrations.CreateModel(
            name='Position2Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.CompanyHring')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Resume')),
            ],
            options={
                'db_table': 'position_resume',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.PositionType'),
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('school_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='学校名称')),
                ('education', models.CharField(blank=True, max_length=16, null=True, verbose_name='学历')),
                ('major', models.CharField(blank=True, max_length=16, null=True, verbose_name='专业')),
                ('entry_time', models.DateField(blank=True, null=True, verbose_name='入学时间')),
                ('graduate_time', models.DateField(blank=True, null=True, verbose_name='毕业时间')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教育经历',
                'db_table': 'education_experience',
            },
        ),
        migrations.AddField(
            model_name='companyhring',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.StoreAuthentication'),
        ),
        migrations.AddField(
            model_name='companyhring',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Position'),
        ),
    ]
