# Generated by Django 3.0.3 on 2020-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('on', '招聘中'), ('stop', '暂停招聘'), ('full', '招满')], default='on', max_length=6)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
